#!/bin/bash
set -o errexit
set -o nounset
traperr() {
    echo "ERROR: ${BASH_SOURCE[1]} at about ${BASH_LINENO[0]}"
}

set -o errtrace
trap traperr ERR

if [[ ! $(which nix-build) ]]; then
    echo "Nix isn't installed and/or in the PATH"
    exit 1
fi

if [[ -f glove81.uf2 ]]; then
    rm -f glove81.uf2
fi
nix-build -A glove81_combined -o combined
cp combined/glove81.uf2 glove81.uf2
